defmodule Glossary.Entries.Entry do
  @moduledoc """
  Schema for glossary entries.

  ## Fields

    * `title` - The entry title (required)
    * `subtitle` - A short description or tagline (required)
    * `body` - Rich text content as HTML, edited via Tiptap (required)
    * `body_text` - Plain text version of body for AI analysis and search (optional, derived from body)

  ## Rich Text Editing

  The `body` field contains HTML generated by the Tiptap editor on the frontend.
  The `body_text` field contains the plain text equivalent, useful for:

    * Vector embeddings and semantic search
    * Full-text search indexing
    * LLM context (avoids wasting tokens on HTML tags)
  """
  use Ecto.Schema
  import Ecto.Changeset

  schema "entries" do
    field :title, :string
    field :title_text, :string
    field :subtitle, :string
    field :subtitle_text, :string
    field :body, :string
    field :body_text, :string

    timestamps(type: :utc_datetime)
  end

  @doc """
  Builds a changeset for an entry.

  ## Params

    * `title` - Entry title (required)
    * `subtitle` - Short description (required)
    * `body` - HTML content from Tiptap editor (required)
    * `body_text` - Plain text content (optional, set by Tiptap hook)
  """
  def changeset(entry, attrs) do
    entry
    |> cast(attrs, [:title, :subtitle, :body, :body_text, :title_text, :subtitle_text])
  end
end
